services:
  web:
    build: ./infra
    ports:
      - "${HTTP_PORT:-8080}:80"
    volumes:
      - ./:/var/www/html
    environment:
      - YAML_PATH=${YAML_PATH:-./openapi.yaml}
    working_dir: /var/www/html
